[project]
name = "lambda-handler"
version = "0.1.0"
description = "AWS Lambda handler"
authors = [{name = "Daichi Narushima", email = "dceoy@users.noreply.github.com"}]
maintainers = [{name = "Daichi Narushima", email = "dceoy@users.noreply.github.com"}]
requires-python = ">=3.12"
dependencies = [
  "aws-lambda-powertools[tracer] >= 3.31.0",
  "awslambdaric >= 4.0.1",
]

[project.urls]
homepage = "https://github.com/dceoy/terraform-aws-docker-based-lambda"
repository = "https://github.com/dceoy/terraform-aws-docker-based-lambda.git"

[dependency-groups]
dev = [
  "ruff >= 0.15.20",
  "pyright >= 1.1.414",
]

[tool.ruff]
line-length = 88
exclude = ["build", ".venv"]
preview = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "CPY",  # flake8-copyright (CPY)
  "RET",  # flake8-return (RET)
  "missing-trailing-comma",
  "function-call-in-default-argument",
  "builtin-import-shadowing",
  "boolean-type-hint-positional-argument",
  "boolean-default-value-positional-argument",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pyright]
typeCheckingMode = "strict"
exclude = ["build", ".venv"]
