---
services:
  lambda-hello-world:
    container_name: lambda-hello-world
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        provenance: false
        platforms:
          - linux/arm64
          # - linux/amd64
    image: lambda-hello-world:latest
    platform: linux/arm64
    entrypoint:
      - /var/lang/bin/python
      - -m
      - awslambdaric
    command:
      - app.lambda_handler
