---
version: '3'
services:
  lambda-hello-world:
    container_name: lambda-hello-world
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        provenance: false
        #  platforms:
        #   - linux/arm64/v8
        #   - linux/arm64
        #   - linux/amd64
    image: dceoy/lambda-hello-world:latest
    # platform: linux/arm64/v8
    entrypoint:
      - /var/lang/bin/python
      - -m
      - awslambdaric
    command:
      - app.lambda_handler
